function [BW,maskedImage] = WaterShedExample(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 22-May-2020
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Create empty mask.
BW = false(size(X,1),size(X,2));

% Flood fill
row = 200;
column = 317;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 105;
column = 136;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 200;
column = 220;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 232;
column = 267;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 257;
column = 306;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 360;
column = 358;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 457;
column = 494;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 436;
column = 388;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 179;
column = 175;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 78;
column = 430;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 24;
column = 505;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 142;
column = 264;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 298;
column = 395;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 548;
column = 352;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 80;
column = 34;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 330;
column = 476;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 287;
column = 510;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 352;
column = 541;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 354;
column = 462;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 499;
column = 361;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 496;
column = 264;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 541;
column = 508;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 530;
column = 480;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 20;
column = 411;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 22;
column = 375;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 438;
column = 457;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 533;
column = 452;
tolerance = 12;
addedRegion = grayconnected(X, row, column, tolerance);
BW = BW | addedRegion;

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

